DB_HOST = 'localhost'
DB_NAME = 'us'
DB_USER = 'postgres'
DB_PASS = 'buddyrich134'
LINE_URL = 'https://notify-api.line.me/api/notify'
LINE_TOKEN = 'lELIMDVI61IYglxYupkOfvPzXsTH5JHunSjH3gwrWAG'
LINE_US30_TOKEN = 'cuMwNs6qoGkWesOUqOPevW0jRfYFoJ5o3K7iT1TSX8W'
LINE_TOKEN_FIRST_MINUTES = 'cl7cyYP65b9RKmuFj0asFklxeapyaYlZDW97mn1jl6O'